# projConfig.toml for xlReg_go

[meta]
    version = '0.1.0'

[project]
    name = 'xlReg_go'  # distro name
    package = 'xlReg_go'  # internal name
    proj_dir = '/home/jdd/dev/go/src/github.com/jddixon/xlReg_go'
    main_lang = 'go'
    version = '1.9.23'
    version_date = '2017-10-21'
    author = 'Jim Dixon'
    author_email = 'jddixon@gmail.com'
    copyright = '2014-2017'
    description = 'registry to manage construction of clusters'
    dev_status = 'beta'
    license = 'mit'
    state = 'shared'
    url = 'https://jddixon.github.io/xlReg_go'

[go]
    cmds=['xlReg']
